$font = Hack Nerd Font

general {
    hide_cursor = false
}

animations {
    enabled = true
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    path = /home/st4v/Pictures/sddm-background.jpg
}

label {
    monitor =
    text = $TIME
    font_size = 90
    font_family = $font
    color = rgb(232, 227, 216)

    position = 0, 180
    halign = center
    valign = center
}

label {
    monitor =
    text = cmd[update:60000] date +"%A, %d %B %Y"
    font_size = 22
    font_family = $font
    color = rgb(232, 227, 216)

    position = 0, 130
    halign = center
    valign = center
}

label {
    monitor =
    text = $USER
    font_size = 20
    font_family = $font
    color = rgb(232, 227, 216)

    position = 0, 85
    halign = center
    valign = center
}

input-field {
    monitor =
    size = 280, 44
    outline_thickness = 2
    inner_color = rgba(26, 26, 26, 1.0)

    outer_color = rgba(cc6633ee)
    check_color = rgba(e8823dee)
    fail_color = rgba(da4453ee)

    font_color = rgb(232, 227, 216)
    fade_on_empty = false
    rounding = 6

    font_family = $font
    placeholder_text = Input password...
    fail_text = $PAMFAIL$FPRINTFAIL

    dots_spacing = 0.3

    position = 0, 30
    halign = center
    valign = center
}

label {
    monitor =
    text = $LAYOUT[us,gr]
    font_size = 14
    font_family = $font
    color = rgb(232, 227, 216)
    onclick = hyprctl switchxkblayout all next

    position = 0, -15
    halign = center
    valign = center
}
